Mother_age = int(input("Enter your mother's age: "))
Father_age = int(input("Enter your father's age: "))
Baby_age = int(input("Enter your baby's age: "))
print("Equal:",Mother_age == Father_age)
print("Not Equal:",Mother_age != Baby_age)
print("Greater than:",Father_age > Baby_age)
print("Less than:",Mother_age < Father_age)
print("Greater than or equal to:",Father_age >= Baby_age)
print("Less than or equal to:",Mother_age <= Father_age)