name = input("mother's name: ")
father = input("father's name: ")
baby = input("baby's name:")
mother_age = input("mother's age: ")
father_age = input("father's age: ")  
baby_age = input("baby's age: ")
print("Mother's name is", name) 
print("Father's name is", father)
print("Baby's name is", baby)
print("Mother's age is", mother_age)
print("Father's age is", father_age)
print("Baby's age is", baby_age)