Name = input("Enter your name: ")
age = input("Enter your age: ")
Branch = input("Enter your branch: ")
student_id = input("Enter your student id: ")
seat_name = input("Enter your seat name: ")
print("Name is", Name)
print("Age is", age)    
print("Branch is", Branch)
print("Student id is", student_id)
print("Seat name is", seat_name)