Mother_age = int(input("Enter your mother's age: "))
Father_age = int(input("Enter your father's age: "))
Baby_age = int(input("Enter your baby's age: "))
print("Mother is Father:",Mother_age == Father_age)
print("Mother is not Father:",Mother_age != Father_age)
print("Mother is Baby:",Mother_age == Baby_age)
print("Mother is not Baby:",Mother_age != Baby_age)
print("Father is Baby:",Father_age == Baby_age)
print("Father is not Baby:",Father_age != Baby_age)