Mother_age = int(input("Enter your mother's age: "))
Father_age = int(input("Enter your father's age: "))
Baby_age = int(input("Enter your baby's age: "))
print("Addition:",Mother_age + Father_age)
print("Subtraction:",Mother_age - Father_age)
print("Multiplication:",Mother_age * Baby_age)
print("Division:",Mother_age / Father_age)
print("Modulus:",Father_age % Baby_age)
print("Power:",Baby_age ** Mother_age)
print("Floor Division:",Father_age // Baby_age)